### ISSUE TITLE
[TODO] App has no user registration or login functionality

### ISSUE THREAD

**Issue by gbowne1** [gbowne1/reactsocialnetwork#8]
**Describe the bug**
[App]

User is not able to register or login or logout to the app/site.  There is a login button (arrow and square bracket) and user icon with no/incomplete functionality.  

Assume NodeJS, Express and MongoDB/Mongoose.

- [ ] Create a Login/Logout panel accessible from User Icon / Avatar menu
- [ ] Create a User Registration / Signup component
- [ ] other issues (placeholder)

Use MaterialUI

**To Reproduce**

Run the dev server with npm start in the root dir. May need to `npm i` or `npm install` the app as I did not include my local node_modules dir. in the upload

**Expected behavior**

- Able to login
- Able to register
- Able to logout
- Able to add user
- Able to create profile

**Desktop (please complete the following information):**
   Linux, 64bit
   Firefox, Chrome
   107

**Additional context**

**Comment by gbowne1** [comment]
My initial idea is to use Axios and JWT's, useState/useEffect hooks, Context API possibly custom hooks for this.

The login form should be simple. 
 - User Name
 - Email
 - Password

Should also have some "Already a member?" and/or "Need an account? Sign up!" link which redirects
Forgot Password link/redirect w/form
Show/Hide "Eye" to hide or show password 

Toasts/Poppers: 
- Incorrect password
- Incorrect username
- Login success!

**Comment by maddy020** [comment]
Hey I would like to work on this issue
Please assign it to me

**Comment by gbowne1** [comment]
Ok @maddy020 Thank you.  I have assigned you.

**Comment by manuel12** [comment]
I will work on this, I have an idea how to mock-implement this without a backend for the time being.

**Comment by gbowne1** [comment]
Ok @manuel12  :-) yeah. I Struggled a bit on which to do first backend or frontend.  Assume that we are using MongoDB at least for the time being.  But having the UI in place will help immensely we can then pretty much choose any backend without too much work.

Oh and I wanna get started on the ERP / MRP as soon as possible as it has not worked for a few years so seeing a PR there will help immensely. I wanna see it work again.

**Comment by manuel12** [comment]
Ok so, UI-wise the login/register screen will be a layer in front of the currently working app.

I was thinking on  implementing this solution with hardcoded values for now, so we can we can get this component out of the way while we wait for the backend. 

For now the login values will be something like username: "testuser1" and password "testpass1".  Once the user has entered the values the layer will give way to the home page where we show the dashboard.

I'm planning to create something like this (also built with Material UI):

![image](https://user-images.githubusercontent.com/4129325/222246551-6e0553de-1053-43df-90a4-b26823f679bc.png)


I will add the remember me checkbox(which is missing in the example above) and also prepare some solution for registration, probably will use localStorage for that for now.

**Comment by gbowne1** [comment]
That's a great idea, @manuel12 .  I plan on having a marketing site to go with this so it could also work directly from the site.  Yeah I wanna make sure that the UI is dialed in before we focus on the backend.  Yeah we can use the browsers stuff to test out in development.  I thought about some initial splash screens as well.

Make sure we also have password strength indication as one Upper case, lower  case, a symble and a number with a minimum of 8 characters.  In the future we can also auth through a service.  Axios is already installed.  Mobile can get a page loading spinner?
